import type { TMangaFaceKeys, TSvgElement } from "@jf/types";

const eyesList: TSvgElement[] = [
  {
    id: 1111,
    name: "eye",
    x: 0,
    y: 0,
    width: 50,
    height: 50,
    path: "https://res.cloudinary.com/db00tntyg/image/upload/v1688134578/Manga/f8wsxipnjdtv79r3fwsn.svg",
  },
  {
    id: 2368,
    name: "eye2",
    x: 0,
    y: 0,
    width: 50,
    height: 50,
    path: "https://res.cloudinary.com/db00tntyg/image/upload/v1688134573/Manga/whhhmmfpvomvb8kovkle.svg",
  },
  {
    id: 35874,
    name: "eye3",
    x: 0,
    y: 0,
    width: 50,
    height: 50,
    path: "https://res.cloudinary.com/db00tntyg/image/upload/v1688134566/Manga/f76jxjr7uaprcftmi7i6.svg",
  },
];

export const list: Record<TMangaFaceKeys, TSvgElement[]> = {
  head: [
    {
      id: 1,
      name: "head1",
      typeOf: "head",
      x: 0,
      y: 0,
      width: 50,
      height: 50,
      path: "https://res.cloudinary.com/db00tntyg/image/upload/v1688392151/Manga/o3rif3cyptmtc8i6jbkj.svg",
    },
  ],
  leftEye: eyesList,
  rightEye: eyesList,
  nose: [
    {
      id: 2,
      name: "nose1",
      typeOf: "nose",
      x: 0,
      y: 0,
      width: 50,
      height: 50,
      path: "https://res.cloudinary.com/db00tntyg/image/upload/v1688134777/Manga/k5mgunruk8fn8ubl8zxn.svg",
    },
    {
      id: 3,
      name: "nose2",
      typeOf: "nose",
      x: 0,
      y: 0,
      width: 50,
      height: 50,
      path: "https://res.cloudinary.com/db00tntyg/image/upload/v1688134772/Manga/n76enlqy3s3vv1lyqscp.svg",
    },
    {
      id: 4,
      name: "nose3",
      typeOf: "nose",
      x: 0,
      y: 0,
      width: 50,
      height: 50,
      path: "https://res.cloudinary.com/db00tntyg/image/upload/v1688134766/Manga/hfefabbigqhm0tyhey12.svg",
    },
    {
      id: 5,
      name: "nose4",
      typeOf: "nose",
      x: 0,
      y: 0,
      width: 50,
      height: 50,
      path: "https://res.cloudinary.com/db00tntyg/image/upload/v1688134760/Manga/ucduurj0s767wiip62mh.svg",
    },
    {
      id: 6,
      name: "nose5",
      typeOf: "nose",
      x: 0,
      y: 0,
      width: 50,
      height: 50,
      path: "https://res.cloudinary.com/db00tntyg/image/upload/v1688134755/Manga/iic2pucurhb5k8lshffy.svg",
    },
  ],
  mouth: [
    {
      id: 7,
      name: "mouth1",
      typeOf: "mouth",
      x: 0,
      y: 0,
      width: 50,
      height: 50,
      path: "https://res.cloudinary.com/db00tntyg/image/upload/v1688134640/Manga/brge8m6ut8ejgxdjkcmw.svg",
    },
    {
      id: 8,
      name: "mouth2",
      typeOf: "mouth",
      x: 0,
      y: 0,
      width: 50,
      height: 50,
      path: "https://res.cloudinary.com/db00tntyg/image/upload/v1688134635/Manga/brhd2kdmvncocxjy0j7g.svg",
    },
    {
      id: 9,
      name: "mouth3",
      typeOf: "mouth",
      x: 0,
      y: 0,
      width: 50,
      height: 50,
      path: "https://res.cloudinary.com/db00tntyg/image/upload/v1688134631/Manga/hgwoaiogk0dcyeyvkgiy.svg",
    },
    {
      id: 10,
      name: "mouth4",
      typeOf: "mouth",
      x: 0,
      y: 0,
      width: 50,
      height: 50,
      path: "https://res.cloudinary.com/db00tntyg/image/upload/v1688134626/Manga/vljdcn5jejjazjlp9dv8.svg",
    },
    {
      id: 11,
      name: "mouth5",
      typeOf: "mouth",
      x: 0,
      y: 0,
      width: 50,
      height: 50,
      path: "https://res.cloudinary.com/db00tntyg/image/upload/v1688134622/Manga/wtmggngcqu8zmrbrpe91.svg",
    },
    {
      id: 12,
      name: "mouth6",
      typeOf: "mouth",
      x: 0,
      y: 0,
      width: 50,
      height: 50,
      path: "https://res.cloudinary.com/db00tntyg/image/upload/v1688134615/Manga/wjou0hennj76cibbvssq.svg",
    },
  ],
  hair: [
    {
      id: 13,
      name: "hair1",
      typeOf: "hair",
      x: 0,
      y: 0,
      width: 50,
      height: 50,
      path: "https://res.cloudinary.com/db00tntyg/image/upload/v1688134689/Manga/kfdtcuqcce8jwfruedhf.svg",
    },
    {
      id: 14,
      name: "hair2",
      typeOf: "hair",
      x: 0,
      y: 0,
      width: 50,
      height: 50,
      path: "https://res.cloudinary.com/db00tntyg/image/upload/v1688134683/Manga/azvnfzucxwimccs8lnah.svg",
    },
  ],
};
