import { JapanLocation } from "./japanData";

export const building: JapanLocation[] = [
  {
    name: "Pop Life Department m's",
    description: `Le magazin pour adulte le plus fun de la plannette. Boutique érotique dans Arrondissement spécial de Tokyo, Japon`,
    city: "Tokyo",
    tag: "building",
    picture: `https://www.tokyoweekender.com/wp-content/uploads/2018/05/Ms-Life-Exterior-of-Store.jpg`,
    links: [""],
    address: `Japon, 〒101-0021 Tokyo, Chiyoda City, Sotokanda, 1 Chome−15−13 太平堂ビルB1F-6F`,
    lat: 35.697603,
    lng: 139.772525,
  },
  {
    name: "Yadobashi-Akiba",
    description: `Le plus grans magazin électronique du monde, c'est ici aussi qu'on retrouve tout ce qui est maid café`,
    city: "Tokyo",
    tag: "building",
    picture: `https://res.cloudinary.com/db00tntyg/image/upload/v1689278756/JAPAN/zq4490nnabofzxu81bdo.png`,
    links: [""],
    address: `1-1 Kanda Hanaokacho, Chiyoda City, Tokyo 101-0028, Japon`,
    lat: 35.699178,
    lng: 139.774345,
  },
  {
    name: "Mairie de Tokyo",
    description: `Meilleur point de vue gratuit sur tokyo. On peux monter tout en haut. Meilleure observatoire de la ville. Et c'est la mairie la plus grande du monde.`,
    city: "Tokyo",
    tag: "building",
    picture: `https://res.cloudinary.com/db00tntyg/image/upload/v1689279431/JAPAN/briqudjc2alxy8yomwmi.png`,
    links: [""],
    address: `2 Chome-8-1 Nishishinjuku, Shinjuku City, Tokyo 163-8001, Japon`,
    lat: 35.688875,
    lng: 139.709611,
  },
  {
    name: "MAGASIN NINTENDO",
    description: `SHIBUYA - LE seul magasin Nintendo au monde, au sixième étage du batiment parko`,
    city: "Tokyo",
    tag: "building",
    picture: `https://res.cloudinary.com/db00tntyg/image/upload/v1689282269/JAPAN/nrlfkusylb4t42qwjg16.png`,
    links: [""],
    address: `Japon, 〒150-0042 Tokyo, Shibuya City, Udagawacho, 15−1 渋谷PARCO 6F`,
    lat: 35.662344,
    lng: 139.698764,
  },
  {
    name: "Sunshine city",
    description: `Sunshine City est un complexe de bâtiments localisés dans l'est d'Ikebukuro, Toshima, Tokyo. Sunshine City est la plus vieille « ville dans une autre ville » de Tokyo, avec le gigantesque et prestigieux gratte-ciel du Sunshine 60 localisé en son centre.`,
    city: "Tokyo",
    tag: "building",
    picture: `https://res.cloudinary.com/db00tntyg/image/upload/v1689414764/JAPAN/tn8gv37gphzxkcdf0htk.png`,
    links: [""],
    address: `3 Chome-1 Higashiikebukuro, Toshima City, Tokyo 170-8630, Japon`,
    lat: 35.730507,
    lng: 139.717586,
  },

  {
    name: "DIVER CITY TOKYO PLAZA",
    description: `Odaiba est le point névralgique des animations avec sa grande roue géante, ses salles de concert, ses salles d'arcades et ses nombreux magasins. Ce quartier peut aussi être fier de l'établissement de sources chaudes Oedo-onsen-monogatari qui recrée l'ambiance traditionnelle de l'époque d'Edo et qui est très prisé des visiteurs étrangers. Shiodome est un quartier qui accueille des immeubles de bureau ultra modernes et des restaurants aux étages supérieurs qui offrent une vue imprenable sur Tokyo.`,
    city: "Tokyo",
    tag: "building",
    picture: `https://res.cloudinary.com/db00tntyg/image/upload/v1689416592/JAPAN/hzmyliwqqdjmgj4ga4gm.png`,
    links: [""],
    address: `1 Chome-1-10 Aomi, Koto City, Tokyo 135-0064, Japon`,
    lat: 35.625899,
    lng: 139.776799,
  },

  // https://res.cloudinary.com/db00tntyg/image/upload/v1689418548/JAPAN/xnbilgubp9taivjch3ed.png

  {
    name: "NAKANO BROADWAY",
    description: `Un truc cool avec ce magazin, c'est qu'il est pas du tout moderne, il est dans le style des vieux magazin du japon. Nakano Broadway est réputée pour être un haut lieu de vente pour otaku (mangas, jeux vidéos, figurines) au Japon`,
    city: "Tokyo",
    tag: "building",
    picture: `https://res.cloudinary.com/db00tntyg/image/upload/v1689418548/JAPAN/xnbilgubp9taivjch3ed.png`,
    links: [""],
    address: `5 Chome-52-15 Nakano, Nakano City, Tokyo 164-0001, Japon`,
    lat: 35.709987,
    lng: 139.665585,
  },

  {
    name: "Ryogoku",
    description: `Le quartier des Sumo à Tokyo. On peux voir gratuitement les entrainement des sumo en passant. Le quartier Ryōgoku, en bord de fleuve, comprend le centre sportif Ryōgoku Kokugikan, qui accueille des tournois de sumo et de boxe, ainsi que des concerts de musique classique. Située à proximité, la rue Ryōgoku Edo Noren, semblable à un village de l'époque d'Edo, regorge de restaurants servant du chankonabe, un ragoût traditionnel riche en protéines et apprécié des lutteurs.`,
    city: "Tokyo",
    tag: "building",
    picture: `https://res.cloudinary.com/db00tntyg/image/upload/v1689419881/JAPAN/hvuwsqifqvefjic4wcvb.png`,
    links: [""],
    address: ``,
    lat: 0,
    lng: 0,
  },

  //   {
  //     name: "",
  //     description: ``,
  //     city: "Tokyo",
  //     tag: "building",
  //     picture: ``,
  //     links: [""],
  //     address: ``,
  //     lat: 0,
  //     lng: 0,
  //   },
];
