import { JapanLocation } from "./japanData";

export const sanctuary: JapanLocation[] = [
  {
    id: "1c4b0a3d-87a0-40e5-8716-ed654d1366d7",
    name: "Meiji-jingū",
    description: `A VISITER ABSOLUMENT LE DIMANCHE ! Il ya des mariages ancestral chaque dimanche, et même parfois plusieurs. Le deuxième plus grans temple de Tokyo. Magnifique chemin de balade forêt.Le sanctuaire Meiji est un sanctuaire shinto à Shibuya, Tokyo, dédié aux esprits déifiés de l'empereur Meiji et de son épouse, l'impératrice Shōken. Le sanctuaire ne contient pas la tombe de l'empereur, qui est située à Fushimi-momoyama, au sud de Kyoto.`,
    city: "Tokyo",
    tag: "sanctuary",
    picture: `https://blog.japanwondertravel.com/wp-content/uploads/2021/03/1582531_l-scaled.jpg`,
    links: [],
    address: `1-1 Yoyogikamizonocho, Shibuya City, Tokyo 151-8557, Japon`,
    lat: 35.676046,
    lng: 139.703697,
  },
  {
    id: "04c6b9be-cd2a-4dad-a3ee-11f02cfe2a8d",
    name: "ASAKUSA - Sensō-ji",
    description: `[GRATUIT] - Venir ici que pour la ballade. Ne pas consomer de nouriture ici, très touristique bouffe pas ouf. Asakusa possède l'atmosphère du vieux Tokyo, avec ses boutiques artisanales traditionnelles et ses étals proposant une cuisine de rue le long de Nakamise Street, près de l'ancien temple Sensō-ji.`,
    city: "Tokyo",
    tag: "sanctuary",
    picture: `https://res.cloudinary.com/db00tntyg/image/upload/v1689276015/JAPAN/mrhwxjlwmlvitlmnvoou.png`,
    links: [],
    address: `2 Chome-3-1 Asakusa, Taito City, Tokyo 111-0032, Japon`,
    lat: 35.713428,
    lng: 139.796721,
  },
  {
    id: "158f710a-8f5e-48da-a72e-dbecfbcc1683",
    name: "Kanda Myojin",
    description: `Le Kanda-myōjin, anciennement Kanda-jinja, est un sanctuaire shinto situé à Chiyoda, l'un des vingt-trois arrondissements de Tokyo, au Japon. Le sanctuaire a mille deux cent soixante-dix ans d'âge mais la structure principale a été reconstruite plusieurs fois à cause d'incendies ou de séismes`,
    city: "Tokyo",
    tag: "sanctuary",
    picture: `https://res.cloudinary.com/db00tntyg/image/upload/v1689278966/JAPAN/tonwtmnqvmb5cogvnm6m.png`,
    links: [],
    address: `2 Chome-16-2 Sotokanda, Chiyoda City, Tokyo 101-0021, Japon`,
    lat: 35.702314,
    lng: 139.768055,
  },
  // {
  //   name: "",
  //   description: ``,
  //   city: "Tokyo",
  //   tag: "sanctuary",
  //   picture: ``,
  //   links: [],
  //   address: ``,
  // },
];
