import Head from "next/head";
import { MangaMakerWrapper } from "@jf/ui-manga-maker";
import { TMangaFace } from "@jf/types";

const mangaFaceBase: TMangaFace = {
  head: {
    id: 1,
    x: 0,
    y: 0,
    width: 50,
    height: 50,
    path: "https://res.cloudinary.com/db00tntyg/image/upload/v1688392151/Manga/o3rif3cyptmtc8i6jbkj.svg",
  },
  // leftEye: {
  //   id: 1,
  //   x: 0,
  //   y: 0,
  //   width: 50,
  //   height: 50,
  //   path: "https://res.cloudinary.com/db00tntyg/image/upload/v1688134573/Manga/whhhmmfpvomvb8kovkle.svg",
  // },
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <SvgEditor /> */}
        <MangaMakerWrapper row={mangaFaceBase} />
      </main>
    </>
  );
}
