import {
  MapPinOnsen,
  MapPinResto,
  MapPinPlane,
  MapPinHotel,
  MapPinSanctuary,
  MapPinPark,
  MapPinBuilding,
  MapPinMonument,
  MapPinStreet,
  MapPinIsland,
  MapPinNeighborhood,
  MapPinActivity,
  MapPinMount,
  MapPinDefault,
  MapPinStation,
  MapPinUniversalStudio,
  MapPinCity,
  MapPinCascade,
  MapPinPokeCafe,
  MapPinPokeCenter,
  MapPinTokyoTower,
  MapPinNintendo,
  MapPinCableCar,
  MapPinFestival,
  MapPinVelo,
  IconToolsKitchen2,
  IconQuestionMark,
  IconBath,
  IconPlaneTilt,
  IconZzz,
  IconTorii,
  IconFlower,
  IconBuildingSkyscraper,
  IconBuildingArch,
  IconRoad,
  IconBeach,
  IconBrandLaravel,
  IconRun,
  IconMountain,
  IconTrain,
  IconBuildingFortress,
  IconRipple,
  IconPokeball,
  IconBuildingLighthouse,
  IconBuildingCarousel,
  IconAerialLift,
  IconBike,
  IconSparkles,
} from "@jf/icons";

export const tagList = [
  {
    value: "restaurant",
    label: "Restaurant",
    icon: MapPinResto,
    defaultIcon: IconToolsKitchen2,
  },
  {
    value: "default",
    label: "Autre",
    icon: MapPinDefault,
    defaultIcon: IconQuestionMark,
  },
  { value: "onsen", label: "Onsen", icon: MapPinOnsen, defaultIcon: IconBath },
  {
    value: "plane",
    label: "Avion",
    icon: MapPinPlane,
    defaultIcon: IconPlaneTilt,
  },
  { value: "hotel", label: "Hotel", icon: MapPinHotel, defaultIcon: IconZzz },
  {
    value: "sanctuary",
    label: "Sanctuaire",
    icon: MapPinSanctuary,
    defaultIcon: IconTorii,
  },
  {
    value: "park",
    label: "Parc/Jardin",
    icon: MapPinPark,
    defaultIcon: IconFlower,
  },
  {
    value: "building",
    label: "Batiment",
    icon: MapPinBuilding,
    defaultIcon: IconBuildingSkyscraper,
  },
  {
    value: "monument",
    label: "Monument",
    icon: MapPinMonument,
    defaultIcon: IconBuildingArch,
  },
  { value: "street", label: "Rue", icon: MapPinStreet, defaultIcon: IconRoad },
  { value: "island", label: "Île", icon: MapPinIsland, defaultIcon: IconBeach },
  {
    value: "neighborhood",
    label: "Quartier",
    icon: MapPinNeighborhood,
    defaultIcon: IconBrandLaravel,
  },
  {
    value: "activity",
    label: "Activité",
    icon: MapPinActivity,
    defaultIcon: IconRun,
  },
  {
    value: "mount",
    label: "Mont",
    icon: MapPinMount,
    defaultIcon: IconMountain,
  },
  {
    value: "station",
    label: "Gare",
    icon: MapPinStation,
    defaultIcon: IconTrain,
  },
  {
    value: "city",
    label: "Ville",
    icon: MapPinCity,
    defaultIcon: IconBuildingFortress,
  },
  {
    value: "cascade",
    label: "Cascade",
    icon: MapPinCascade,
    defaultIcon: IconRipple,
  },
  {
    value: "poke-cafe",
    label: "Poké-Café",
    icon: MapPinPokeCafe,
    defaultIcon: IconPokeball,
  },
  {
    value: "poke-center",
    label: "Poké-Café",
    icon: MapPinPokeCenter,
    defaultIcon: IconPokeball,
  },
  {
    value: "tokyo-tower",
    label: "tokyo-tower",
    icon: MapPinTokyoTower,
    defaultIcon: IconBuildingLighthouse,
  },
  {
    value: "nintendo-shop",
    label: "Magasin Nintendo",
    icon: MapPinNintendo,
    defaultIcon: IconBuildingCarousel,
  },
  {
    value: "cable-car",
    label: "Téléphérique",
    icon: MapPinCableCar,
    defaultIcon: IconAerialLift,
  },
  { value: "velo", label: "Vélo", icon: MapPinVelo, defaultIcon: IconBike },
  {
    value: "festival",
    label: "Festival",
    icon: MapPinFestival,
    defaultIcon: IconSparkles,
  },
  {
    value: "universal-studio",
    label: "Universal Studio",
    icon: MapPinUniversalStudio,
    defaultIcon: IconBuildingCarousel,
  },
];
