import {
  MapPinOnsen,
  MapPinResto,
  MapPinPlane,
  MapPinHotel,
  MapPinSanctuary,
  MapPinPark,
  MapPinBuilding,
  MapPinMonument,
  MapPinStreet,
  MapPinIsland,
  MapPinNeighborhood,
  MapPinActivity,
  MapPinMount,
  MapPinDefault,
  MapPinStation,
  MapPinUniversalStudio,
  MapPinCity,
  MapPinCascade,
} from "@jf/icons";

export const tagList = [
  { value: "restaurant", label: "Restaurant", icon: MapPinResto },
  { value: "onsen", label: "Onsen", icon: MapPinOnsen },
  { value: "plane", label: "Avion", icon: MapPinPlane },
  { value: "hotel", label: "Hotel", icon: MapPinHotel },
  { value: "sanctuary", label: "Sanctuaire", icon: MapPinSanctuary },
  { value: "park", label: "Parc/Jardin", icon: MapPinPark },
  { value: "building", label: "Batiment", icon: MapPinBuilding },
  { value: "monument", label: "Monument", icon: MapPinMonument },
  { value: "street", label: "Rue", icon: MapPinStreet },
  { value: "island", label: "Île", icon: MapPinIsland },
  { value: "neighborhood", label: "Quartier", icon: MapPinNeighborhood },
  { value: "activity", label: "Activité", icon: MapPinActivity },
  { value: "mount", label: "Mont", icon: MapPinMount },
  { value: "station", label: "Gare", icon: MapPinStation },
  { value: "city", label: "Ville", icon: MapPinCity },
  { value: "cascade", label: "Cascade", icon: MapPinCascade },
  {
    value: "universal-studio",
    label: "Universal Studio",
    icon: MapPinUniversalStudio,
  },
];
