import { useState } from "react";
import Head from "next/head";
import LocationCardList from "./LocationCardList";
import { Drawer } from "../components/Drawer/Drawer";
import { JapanLocation } from "../assets/japanData";
import neighborhoods from "./api/tokyo.json";
import { useMapBox } from "@jf/material";
import { useGeoloc } from "@jf/hooks";

export default function Home({
  neighborhoodsData,
}: {
  neighborhoodsData: any;
}) {
  const [currentTag, setCuurentTag] = useState<string | null>("");
  const [view, setView] = useState<string>("map");
  const [currentLocation, setCurrentLocation] = useState<JapanLocation | null>(
    null
  );

  const currentPosition = useGeoloc();

  const [fetch, { viewport, onViewportChange, onCoordinateClick }] =
    useMapBox();

  return (
    <>
      <Head>
        <title>JAPAN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Drawer
          onTagChange={setCuurentTag}
          tag={currentTag || ""}
          onViewChange={setView}
          view={view}
          currentLocation={currentLocation}
          onCurrentLocationChange={setCurrentLocation}
        />

        <LocationCardList
          tag={currentTag || ""}
          view={view}
          viewport={viewport}
          currentPosition={currentPosition}
          onViewportChange={onViewportChange}
          onCoordinateClick={onCoordinateClick}
          onLocationChange={setCurrentLocation}
          currentLocation={currentLocation}
          neighborhoods={neighborhoodsData}
        />
      </main>
    </>
  );
}

export async function getStaticProps() {
  return {
    props: {
      neighborhoodsData: neighborhoods,
    },
  };
}
