import Head from "next/head";
import { Box, Divider, Select } from "@jf/material";
import { useState } from "react";

import { LocationCardList } from "./LocationCardList";

export default function Home() {
  const [currentTag, setCuurentTag] = useState<string | null>("");

  return (
    <>
      <Head>
        <title>JAPAN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box
          sx={{
            position: "sticky",
            top: 0,
            zIndex: 100,
            backgroundColor: "white",
            borderBottomLeftRadius: 8,
            borderBottomRightRadius: 8,
            borderRight: "1px solid gray",
            borderLeft: "1px solid gray",
            borderBottom: "1px solid gray",
          }}
          p="md"
          mb="md"
        >
          <Select
            label="Tag"
            placeholder="Choisit un tag"
            onChange={setCuurentTag}
            data={[
              { value: "", label: "Tout" },
              { value: "neighborhood", label: "Quartier" },
              { value: "sanctuary", label: "Sanctuaire" },
              { value: "park", label: "Parc/Jardin" },
              { value: "activity", label: "Activité" },
              { value: "restaurant", label: "Restaurant" },
              { value: "building", label: "Batiment" },
              { value: "street", label: "Rue" },
            ]}
          />
          <Divider />
        </Box>
        <LocationCardList tag={currentTag || ""} />
      </main>
    </>
  );
}
