import React from "react";

import Head from "next/head";
import { Data } from "@/utils/data/type";

import { CV } from "../CV";

export interface CvPageProps {
  data: Data;
}

export const CvPage = ({ data }: CvPageProps) => {
  return (
    <>
      <Head>
        <title>JF PICHERIT CV</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ height: "100%", padding: 0, margin: 0 }}>
        <CV data={data} />
      </main>
    </>
  );
};
